version: "3.3"
services:
  my-app:
    image: "phuongvd7/testmaster:latest"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    # volumes:
    #   - ".:/usr/share/nginx/html"